manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/indigoblueraspberry
  projects:
    - name: zmk-capslock
      remote: zmkfirmware
      revision: caps-word-for-alt-layouts
      import: app/west.yml
  self:
    path: config
